# fly.toml app configuration file generated for linklocker-cool-morning-7742 on 2024-02-14T23:10:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'linklocker-cool-morning-7742'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
[[mounts]]
  source = 'data'
  destination = '/data'
